language: java
sudo: false
dist: trusty
install: true
addons:
  sonarcloud:
    organization: "alu0100890709-github"
    token:
      secure: "8918b6fcb78cf8fd790d3529e43773664c08c738"
jdk:
  - oraclejdk8
script:
# the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
#JaCoCo is used to have code coverage, the agent has to be activated
  - ./script.sh
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - .autoconf
    - $HOME/.m2
notifications:
  email: 
  recipients:
    - maestre1996@gmail.com
on_success: always
on_failure: always
before_install:
  - chmod +x script.sh
